name: responsvie_dashboard
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_blind_watermark: ^0.0.2
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets :
  assets:
    - assets/images/

  # To add fonts :
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
  #         weight: 700
# flutter assets gen
flutter_assets:
  assets_path: assets/images/
  output_path: lib/utils
  filename: app_images.dart
  field_prefix: null
